// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3j5Js99xvfBiPpLFeqjezkEsR4KwJ1t4',
    appId: '1:1075161981426:web:47c89c7b916b157eff0b6b',
    messagingSenderId: '1075161981426',
    projectId: 'flutterconnect-b3d2a',
    authDomain: 'flutterconnect-b3d2a.firebaseapp.com',
    storageBucket: 'flutterconnect-b3d2a.firebasestorage.app',
    measurementId: 'G-PS7XMZQ2WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04HwxpZjekr6pqfFQ4EZVZXQ60NQgxYw',
    appId: '1:1075161981426:android:5c7b5a66836415c8ff0b6b',
    messagingSenderId: '1075161981426',
    projectId: 'flutterconnect-b3d2a',
    storageBucket: 'flutterconnect-b3d2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQDTaxQdU9ahhayorNtkD0Ma6bOzdMvg',
    appId: '1:1075161981426:ios:5d06f1764ae9e3ecff0b6b',
    messagingSenderId: '1075161981426',
    projectId: 'flutterconnect-b3d2a',
    storageBucket: 'flutterconnect-b3d2a.firebasestorage.app',
    iosBundleId: 'com.brainwired.brainwired',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQDTaxQdU9ahhayorNtkD0Ma6bOzdMvg',
    appId: '1:1075161981426:ios:5d06f1764ae9e3ecff0b6b',
    messagingSenderId: '1075161981426',
    projectId: 'flutterconnect-b3d2a',
    storageBucket: 'flutterconnect-b3d2a.firebasestorage.app',
    iosBundleId: 'com.brainwired.brainwired',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3j5Js99xvfBiPpLFeqjezkEsR4KwJ1t4',
    appId: '1:1075161981426:web:9eecf941f29e0596ff0b6b',
    messagingSenderId: '1075161981426',
    projectId: 'flutterconnect-b3d2a',
    authDomain: 'flutterconnect-b3d2a.firebaseapp.com',
    storageBucket: 'flutterconnect-b3d2a.firebasestorage.app',
    measurementId: 'G-YEZ17BX37F',
  );
}
